twelve test allure

diff --git a/.github/workflows/test-1.yml b/.github/workflows/test-1.yml
--- a/.github/workflows/test-1.yml
+++ b/.github/workflows/test-1.yml
@@ -27,17 +27,15 @@ jobs:
       - name: Install Playwright Browsers
         run: playwright install
 
+      - name: Run tests with pytest + allure
+        run: pytest --alluredir=allure-results
+
       # - name: Run tests with pytest + allure
       #   id: pytest
-      #   continue-on-error: true
-      #   run: pytest --alluredir=allure-results
-
-      - name: Run tests with pytest + allure
-        id: pytest
-        run: |
-          pytest \
-            --alluredir=allure-results \
-            --clean-alluredir || (echo "PYTEST_FAILED=true" >> $GITHUB_ENV)
+      #   run: |
+      #     pytest \
+      #       --alluredir=allure-results \
+      #       --clean-alluredir || (echo "PYTEST_FAILED=true" >> $GITHUB_ENV)
 
       - name: Install Allure CLI
         run: npm install -g allure-commandline --save-dev
@@ -71,6 +69,6 @@ jobs:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: allure-report
 
-      - name: Fail pipeline if tests failed
-        if: steps.pytest.outputs.failed == 'true'
-        run: exit 1
+      # - name: Fail pipeline if tests failed
+      #   if: steps.pytest.outputs.failed == 'true'
+      #   run: exit 1
